@Library("mysharedlibrary")_

pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitDownload('main','maven-1')
                }
            }
        }
        stage('Build')
        {
            steps{
                script{
                    cicd.buildArtifact()
                }
            }
        }
        stage("deploy"){
            steps{
                script{
                    cicd.deployTomcat('libraries','purna','192.168.64.7','testapp')
                }
            }
        }
        stage('test'){
            steps{
                script{
                    cicd.gitDownload('master','Testing')
                    cicd.testApplication('libraries')
                }
            }
        }
        stage('delievery')
        {
            steps{
                script{
                    cicd.deployTomcat('libraries','purnachandra','192.168.64.5','prodapp')
                }
            }
        }
    }
}
